server:
  port: 9090

reporter:
  config:
    enableScheduler: true

spring:
  # Web
  thymeleaf:
    mode: HTML
#    prefix: "/WEB-INF/thymeleaf/"
    suffix: .html
    cache: false
    template-resolver-order: 1
    check-template: true
    check-template-location: true
    
  # JPA
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.jdbc.batch_size: 10
#      hibernate.order_inserts: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: true        
#  h2:
#    console:
#      enabled: true
#  datasource:
#    platform: h2
#    url: jdbc:h2:file:./swh_reporter_db;AUTO_SERVER=TRUE
#    username: admin
#    password: admin
#    driver-class-name: org.h2.Driver
  # Internationalization
  messages:
    basename: messages/messages
#  devtools:
#    livereload:
#      enabled: true
  # Maximum time static resources should be cached
  data:
    mongodb:
      host: localhost
      port: 27017

#  web:
#    resources:
#      cache:
#        cachecontrol:
#          max-age: 12h
#  resources:
#    cache:
#      cachecontrol:
#        max-age: 12h

# Actuator
#management.endpoints.web.exposure.include: *

# Logging
logging:
#  level: INFO
  level.org.springframework: INFO
#  level.org.hibernate.SQL: DEBUG
#  level.org.hibernate.type: TRACE

# logging.level.org.springframework.web: DEBUG
# logging.level.org.springframework.context.annotation: TRACE