server:
  port: 9090

spring:
  # Web
  thymeleaf:
    mode: HTML
#    prefix: "/WEB-INF/thymeleaf/"
    suffix: .html
    cache: false
    template-resolver-order: 1
    check-template: true
    check-template-location: true

  # Internationalization
  messages:
    basename: messages/messages
#  devtools:
#    livereload:
#      enabled: true
  # Maximum time static resources should be cached
#  web:
#    resources:
#      cache:
#        cachecontrol:
#          max-age: 12h
#  resources:
#    cache:
#      cachecontrol:
#        max-age: 12h

# Actuator
#management.endpoints.web.exposure.include: *

# Logging
logging:
  level: INFO
logging.level.org.springframework: INFO
# logging.level.org.springframework.web: DEBUG
# logging.level.org.springframework.context.annotation: TRACE


# database init, supports mysql too
#  database=h2
#  spring.datasource.schema: classpath*:db/${database}/schema.sql
#  spring.datasource.data: classpath*:db/${database}/data.sql

# JPA
#  spring.jpa.hibernate.ddl-auto=none
#  spring.jpa.open-in-view=false